[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/2024.07.00/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
platform_packages =
    platformio/framework-arduinoespressif32-libs @ symlink:///media/secondary/repos/esp32-touchscreen-home-assistant-panel/platformio-touchscreen-src/modified-high-perf-idf-release-5_1/tools/esp32-arduino-libs/idf-release_v5.1-bd2b9390ef

upload_speed = 921600
monitor_speed = 115200

; I don't know if any of these are necessary, I have not tested with them yet, likely some are, like PSRAM

; The below enabled lines are my best guess at matching this:
; https://github.com/esp-arduino-libs/ESP32_Display_Panel/blob/master/docs/board/board_waveshare.md
; In the "Arduino IDE" section.
; If things don't work, I'll try and use the Arduino IDE itself to build and look at flags
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0

;    -LV_CONF_INCLUDE_SIMPLE
;    -DDISABLE_ALL_LIBRARY_WARNINGS
;    -DCORE_DEBUG_LEVEL=1
;    -DLV_LVGL_H_INCLUDE_SIMPLE
;    -I src


lib_deps =
    symlink:///media/secondary/repos/esp32-touchscreen-home-assistant-panel/platformio-touchscreen-src/lib/ESP32_Display_Panel
    symlink:///media/secondary/repos/esp32-touchscreen-home-assistant-panel/platformio-touchscreen-src/lib/ESP32_IO_Expander
    symlink:///media/secondary/repos/esp32-touchscreen-home-assistant-panel/platformio-touchscreen-src/lib/lvgl
    fbiego/ESP32Time @ ^2.0.0
    ayushsharma82/ElegantOTA @ ^3.1.1
    knolleary/PubSubClient @ ^2.8
    pfeerick/elapsedMillis @ ^1.0.6
