[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/2024.07.00/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
platform_packages =
    platformio/framework-arduinoespressif32-libs @ symlink:///media/secondary/repos/esp32-touchscreen-home-assistant-panel/platformio-touchscreen-src/modified-high-perf-idf-release-5_1/tools/esp32-arduino-libs/idf-release_v5.1-bd2b9390ef

upload_speed = 921600
monitor_speed = 115200

lib_deps =
    symlink:///media/secondary/repos/esp32-touchscreen-home-assistant-panel/platformio-touchscreen-src/lib/ESP32_Display_Panel
    symlink:///media/secondary/repos/esp32-touchscreen-home-assistant-panel/platformio-touchscreen-src/lib/ESP32_IO_Expander
    symlink:///media/secondary/repos/esp32-touchscreen-home-assistant-panel/platformio-touchscreen-src/lib/lvgl
    fbiego/ESP32Time @ ^2.0.0
    ayushsharma82/ElegantOTA @ ^3.1.1
    knolleary/PubSubClient @ ^2.8
    pfeerick/elapsedMillis @ ^1.0.6
